import { useEffect, useState } from 'react'
import './App.css'

const navItems = [
  ['01', 'PROFILE', 'profile'], ['02', 'CAPABILITIES', 'capabilities'], ['03', 'WORK', 'work'],
  ['04', 'R&D', 'research'], ['05', 'ACTIVITY', 'activity'], ['06', 'CONTACT', 'contact'],
]
const capabilities = [
  { code: 'AI.01', title: 'AI & LLM', items: ['AI / LLM APIs', 'AI-assisted development', 'Rapid prototyping', 'Product ideation'], accent: 'cyan' },
  { code: 'DEV.02', title: 'DEVELOPMENT', items: ['Vibe coding', 'Web product development', 'API integration', 'UI / UX'], accent: 'blue' },
  { code: 'DATA.03', title: 'BACKEND & DATA', items: ['Supabase', 'MongoDB', 'Firebase'], accent: 'amber' },
  { code: 'BIO.04', title: 'BIOTECHNOLOGY', items: ['Biotechnology fundamentals', 'Bioinformatics - foundational knowledge'], accent: 'green' },
  { code: 'HW.05', title: 'HARDWARE EXPOSURE', items: ['ESP32', 'IoT prototyping', 'BLE / GATT', 'Hardware-software integration'], accent: 'pink' },
]
const certifications = ['Foundation Course in Bioinformatics', 'Introduction to Biotechnology', 'Yuva AI for All', 'Generative AI Mastermind', 'AI Tools & Claude Workshop']
const profileImageUrl = 'https://i.ibb.co/S4yXbmg4/vedang.jpg'

function App() {
  const [booted, setBooted] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  useEffect(() => { const timer = window.setTimeout(() => setBooted(true), 2200); return () => window.clearTimeout(timer) }, [])
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }

  return (
    <div className={`app-shell ${booted ? 'is-booted' : ''}`}>
      {!booted && <div className="boot-screen"><div className="boot-inner"><div className="boot-mark">VS<span>/</span>OS</div><p className="boot-line">INITIALIZING VEDANG.OS<span className="blink">_</span></p><div className="boot-log"><span>LOADING PROFILE MODULE</span><b>OK</b><span>BIOTECH SYSTEM</span><b>OK</b><span>AI MODULE</span><b>OK</b><span>INNOVATION CORE</span><b>OK</b></div><div className="boot-progress"><i /></div><small>SYSTEM ONLINE / 2026.09</small></div></div>}
      <header className="topbar"><button className="brand" onClick={() => scrollTo('top')}><span className="brand-signal" />VEDANG<span className="brand-dot">.</span>SYS</button><div className="top-status"><span className="live-dot" /> SYSTEM ONLINE <span className="status-divider" /> INDIA / 2026</div><button className="menu-button" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span /><span /><span /></button><nav className={menuOpen ? 'nav-open' : ''}>{navItems.map(([number, label, id]) => <button key={id} onClick={() => scrollTo(id)}><small>{number}</small>{label}</button>)}</nav></header>
      <main id="top">
        <section className="hero-section section-wrap"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line" /> PERSONAL R&D CONSOLE / PROFILE_01</p><h1>VEDANG<br /><em>SONI</em></h1><p className="hero-role">Biotechnology student <span>·</span> Product builder <span>·</span> Innovator</p><p className="hero-subtitle">Science in the foundation.<br /><strong>Technology in the build.</strong></p><div className="hero-actions"><button className="primary-button" onClick={() => scrollTo('work')}>EXPLORE WORK <span>+</span></button><button className="text-button" onClick={() => scrollTo('contact')}>ESTABLISH CONNECTION <span>↗</span></button></div></div><div className="hero-visual"><div className="scan-label top-label">BIOMETRIC / PROFILE PHOTO</div><div className="portrait-frame"><div className="portrait-grid" /><div className="portrait-placeholder"><img className="portrait-photo" src={profileImageUrl} alt="Vedang Soni" /><span>VS</span><small>PROFILE<br />IMAGE</small></div><i className="corner tl" /><i className="corner tr" /><i className="corner bl" /><i className="corner br" /></div><div className="scan-label bottom-label"><span>USER: VEDANG SONI</span><span>STATUS: ACTIVE</span></div><div className="orbit orbit-one" /><div className="orbit orbit-two" /></div><aside className="hero-hud"><div><span>FIELD</span><b>BIOTECHNOLOGY</b></div><div><span>MODE</span><b>LEARNING + BUILDING</b></div><div><span>LOCATION</span><b>INDIA</b></div></aside></section>
        <section id="profile" className="profile-section section-wrap section-grid"><div className="section-index">01<span>/</span></div><div className="section-heading"><p className="eyebrow">SYSTEM PROFILE</p><h2>Curiosity,<br /><em>activated.</em></h2></div><div className="profile-content"><div className="terminal-window"><div className="terminal-top"><span>PROFILE.DAT</span><span>READ ONLY</span></div><p><span className="prompt">&gt;</span> A Biotechnology student interested in building technology-driven solutions and exploring the intersection of science, artificial intelligence and product development.</p><div className="terminal-cursor">_</div></div><div className="profile-meta"><div><span>ACADEMIC FIELD</span><b>BIOTECHNOLOGY</b></div><div><span>INTERESTS</span><b>AI / TECH / INNOVATION</b></div><div><span>BUILD MODE</span><b>AI-ASSISTED</b></div><div><span>CURRENT PHASE</span><b>LEARNING + BUILDING</b></div></div></div></section>
        <section id="capabilities" className="capabilities-section section-wrap"><div className="section-topline"><div className="section-index">02<span>/</span></div><div><p className="eyebrow">SYSTEM CAPABILITIES</p><h2>Tools for <em>making.</em></h2></div><p className="section-note">No artificial percentages.<br />Just real exposure.</p></div><div className="capability-grid">{capabilities.map((cap) => <article className={`capability-card ${cap.accent}`} key={cap.code}><div className="card-top"><span>{cap.code}</span><span className="module-ready">MODULE READY</span></div><h3>{cap.title}</h3><ul>{cap.items.map((item) => <li key={item}><span />{item}</li>)}</ul><div className="card-index">{cap.code.slice(-2)}</div></article>)}</div></section>
        <section id="work" className="work-section section-wrap section-grid"><div className="section-index">03<span>/</span></div><div className="section-heading"><p className="eyebrow">VERIFIED CONTRIBUTION</p><h2>Work with<br /><em>meaning.</em></h2></div><div className="work-card"><div className="work-card-main"><div className="work-logo">S<span>&amp;</span>C</div><div><p className="eyebrow">SAFE &amp; CARE / 001</p><h3>Sustainable<br />Hygiene Product Business</h3><p>Contributed to a family business working with biodegradable sanitary pads using bamboo fibre.</p></div></div><div className="work-meta"><span>TYPE <b>FAMILY BUSINESS</b></span><span>DOMAIN <b>SUSTAINABLE HYGIENE</b></span><span>MATERIAL <b>BAMBOO FIBRE</b></span><span>ROLE <b>CONTRIBUTOR</b></span></div></div></section>
        <section id="research" className="research-section section-wrap section-grid"><div className="section-index">04<span>/</span></div><div className="section-heading"><p className="eyebrow">TECHNICAL EXPOSURE</p><h2>Still in the<br /><em>lab.</em></h2></div><div className="research-card"><div className="radar"><div className="radar-cross" /><div className="radar-ring ring-a" /><div className="radar-ring ring-b" /><div className="radar-point" /></div><div className="research-copy"><p className="eyebrow">R&amp;D LOG / ACTIVE</p><h3>Hands-on experimentation with connected systems.</h3><p>ESP32-based IoT systems, BLE/GATT communication and hardware-software integration.</p><div className="tags">{['ESP32', 'BLE', 'GATT', 'IoT', 'EMBEDDED SYSTEMS'].map(tag => <span key={tag}>{tag}</span>)}</div></div></div></section>
        <section id="activity" className="activity-section section-wrap"><div className="section-topline"><div className="section-index">05<span>/</span></div><div><p className="eyebrow">NETWORK.ACTIVITY</p><h2>Learning in <em>public.</em></h2></div></div><div className="activity-list"><article><span className="activity-status" /><div className="activity-number">01</div><div><p className="eyebrow">E-CELL / TECHNICAL TEAM</p><h3>Trainee / Member</h3><p>Technical exposure and participation within the entrepreneurship ecosystem.</p></div><span className="activity-arrow">↗</span></article><article><span className="activity-status amber" /><div className="activity-number">02</div><div><p className="eyebrow">RaIOT / TECHNOLOGY LEARNING</p><h3>Trainee</h3><p>Exposure to IoT and technology-oriented learning.</p></div><span className="activity-arrow">↗</span></article></div><div className="education-strip"><p className="eyebrow">ACADEMIC CORE</p><div><h3>B.Tech Biotechnology</h3><p>Amity University Rajasthan / 2026 - 2030</p></div><div><h3>Class XII</h3><p>MPBSE / Secondary education</p></div></div></section>
        <section className="cert-section section-wrap"><div className="section-topline"><div className="section-index">06<span>/</span></div><div><p className="eyebrow">CERTIFICATION_DATABASE</p><h2>Foundations &amp; <em>signals.</em></h2></div></div><div className="cert-grid">{certifications.map((cert, index) => <div className="cert-card" key={cert}><span>0{index + 1}</span><h3>{cert}</h3><small>VERIFICATION PENDING</small></div>)}</div></section>
        <section id="contact" className="contact-section section-wrap"><div className="contact-main"><p className="eyebrow">ESTABLISH_CONNECTION</p><h2>Want to build<br /><em>something interesting?</em></h2><p>Open to conversations at the intersection of biology, technology and ambitious ideas.</p></div><div className="contact-nodes"><a href="https://www.linkedin.com/in/vedangsoni" target="_blank" rel="noreferrer"><span>01</span><b>LINKEDIN</b><small>PROFESSIONAL NETWORK</small><i>↗</i></a><a href="https://github.com" target="_blank" rel="noreferrer"><span>02</span><b>GITHUB</b><small>BUILDS &amp; EXPERIMENTS</small><i>↗</i></a><a href="mailto:sonivedang7@gmail.com"><span>03</span><b>EMAIL</b><small>DIRECT COMMUNICATION</small><i>↗</i></a></div></section>
      </main><footer><span>VEDANG.SYS / PERSONAL R&amp;D CONSOLE</span><span>BUILT WITH CURIOSITY / <b>STATUS: ACTIVE</b></span></footer>
    </div>
  )
}

export default App
